export default {
  lang:'en',
  halo: 'Hello',
  gantiBahasa:'Change Language',
  pilihBahasa: 'Select Language',
  pengaturanBahasa:'Language Setting',
  judulApp: "Let's Learn Al-Quran With BaQi",
  deskBeranda: "Home",
  deskProfil: "Profile",
  deskProses: "Progress",
  menuOne : "Understand Qur'an",
  menuTwo :"Exam",
  menuTree : "Rangking",
  menuFour : "Group",
  deskMenu1: "Understanding the Qur'an well",
  deskMenu2: "Come Test Your Skills",
  deskMenu3: "See Your Ranking Here",
  deskMenu4: "Join Study Group",
  menuPetro : "Petrophysics & CEOR",
  deskMenuPetro: "Learn Petrophysics & Chemical EOR",
  judulPetro: "Petrophysics & CEOR",
  ujianBab: "End of Chapter Exam",
  baqi_desk: "Interactive Qur'an Language",
  fnama : "Name",
  fnohp : "Phone Number (Optional)",
  femail : "Email",
  infoLogin : "You Sign In With",

  infoLoginform: "Please login to continue",
  fpengguna: "Username",
  fsandi: "Password",
  lupasandi: "Forgot Password?",
  buatakun: "Create Account",
  masuk:"Sign In",
  daftar:"Register",
  atau: "Or",
  masukdengan: "Sign In With",
  daftardengan: "Register With",
  btnfb : "Login with Facebook",
  btngoogle : "Login with Google",
  btnRfb : "Sign up with Facebook",
  btnRgoogle : "Sign up with Google",
  gueslogin  : "Login As Guest",
  keseluruhan : "Totality",
  semangat : "Keep spirit",
  terimakasih : "Thank you",
  st_kerjakan : "Last Worked",
  st_buatkamu : "For You",
  st_notif_prgs : "No exams done yet",

  skor : "Score",
  peringkat : "Ranking",
  totalskor: "Total Score",

  sandiBaru : "New Password",
  us_sandi: "Change Password",
  g_judul : "Group List",
  g_deskrip : "Groups Available",
  lainnya : "Other",
  gpop_judul : "Group Password",
  gpass_desk : "Enter the password to join the group",

  bg_judul : "Form Learning \nCommunity Groups",
  bg_fnama: "Group Name",
  bg_fdesk: "Group Description",
  bg_fpass: "Group Password",
  plc_gnama: "Write your group name",
  plc_gdesk: "Write a group description",
  plc_gsandi: "Make sure it's unique",
  plc_popSandi: "Enter password correctly",
  plc_amnamapg : "Write Username",
  plc_nmpengguna : "Write Username",
  plc_sandi: "Write password",
  plc_email: "Write email address",
  plc_nama: "Full Name",
  plc_sandiv2: "Make sure it's hard to predict",
  plc_nmpenggunav2 : "Make it unique",
  berhasil :"Succeed",
  g_suksesbuat :"Group created successfully...",
  g_mbrkeluar:"Member has been removed",

  txt_ubh_foto:"Change Profile Photo",
  kamera:"Camera",
  galeri:"Gallery",
  pengaturan: "Setting",
  txt_pengaturan: "Photo capture access has not been activated.\nGive access to start taking pictures. Enable photo capture access from Settings.",
  btn_cancel_pgtrn: "Later",
  btn_yes_pgtrn: "Activate",

  konfirmasi:"Confirmation",
  txt_konfimout:"Do you want to go out?",
  txt_konfimgout: "Are you sure you can remove this member?",
  txt_konfimadmout: "Are you sure you want to leave the group? group will be deleted",
  txt_btambahkan: "Added successfully",
  txt_konfirmagt : "Add this user to the group?",
  txt_konfirmdelacct : "Are you sure you want to delete your account?, this action will delete all your data permanently, can't be undone!",
  txt_verivNotice : "If at any time you want to return to using the application, then you have to re-register again",
  txt_codeResend:"Didn't receive the code? Resend",
  hapusAccSukses: "We have deleted your account from the system, if you want to return, please re-register",

  lanjut: "Next",
  cari : "Search",
  keluar : "Sign Out",

  verivicationTitle:"VERIVICATION",
  ubahProfil : "Change Profile",
  simpan  : "Save",
  batal : "Cancel",
  yakin: "I'm Sure",
  gabung : "Join",
  tambah: "Add",
  gsaya : "My Group",
  gbuat : "Create Group",
  gdetail : "Details group",
  gbergabung: "Join Group",
  anggota : "Member",
  mg_judul : "Group Menu",
  mg_menusatu : "Add Member",
  oke:'Okay',
  kembali: "Back",
  gcari:"Find Groups",
  cobalagi : "Try again",
  selamat: "Congratulations",

  ubah: "Change",
  verifikasi: "Verification",
  kirim:"Send",
  tonton: "Watch",
  baca : "Read",
  unduh: "Download",
  unduh_sekarang: "Download Now",
  ujian: "Exam",
  pelajaran: "Lesson",
  pilih_jenis_ujian:"SELECT THE TEST TYPE",
  txt_pilih_ujian:"Please choose the type of exam and complete it well",
  ujian_akhir :"Final Exam",
  final_test : "FINAL TEST",
  grammar_test : "GRAMMAR TEST",
  tatabahasa: "Grammar",
  level: "Level",
  pilih_jenis_test : "Select Test Type",
  txt_pilih_jenis_test : "You have to solve all the questions after the questions appear",

  err_konek : "Unable to connect to server!",
  err_data: "Failed to receive data from server!",
  err_trima: "Unable to receive data",
  dataNull: "Failed to load / Data not yet available!",
  err_404: "Tidak ada data ditemukan!",
  err_500: "An error occurred on the server!",
  err_404V2: "No data found yet...",
  err_update: "Update failed, try again later",
  err_user404:"User not found!",
  err_404V3 : "There is no data for this page yet",
  err_noskor: "You don't have a score yet, please start the test to get a score",
  err_unduh : "Sorry, the document is not available",
  err_unduhV2: "Sorry, the requested document is not ready",
  err_500V2 : "A technical error occurred!",
  err_500V3: "An error occurred on the server, Please try again later!",
  err_404V2Grup : "Wrong group password!",
  err_404V3Grup : "Group does not exist!",
  grup_409join: "You have joined this group before",
  grup_201join: "Welcome to Join, Please check my group list",
  err_sandi: "Enter a password of at least 6 characters",
  err_grpJudul :"Group Title cannot be empty!",
  err_grpDesk :"Description cannot be empty!",
  err_grpSandi :"Password cannot be empty!",
  err_grpMax: "The group has the maximum creation limit!",
  err_duplikatDesk: "Duplicate Description, Description has been used",
  err_batal: "Process Canceled",
  err_proseson: "Process is running",
  err_playservice: "Please Activate Google Play Service",
  err_prosesoff: "Oops, There's an Error!",
  err_pu_salah : "Wrong Username or Password!",
  err_reg409: "Registration Failed, Username/Email has been used!",
  err_regGagal: "Registration Failed, try again later",
  err_namaNull: "Name cannot be empty!",
  err_hpNull: "Mobile number cannot be empty!",
  err_emailNull:"Email cannot be empty!",
  err_emailNsm: "Email entered is not the same!",
  err_unameNull : "Username cannot be empty!",
  err_pswNull   : "Password cannot be empty!",
  err_data500Nr : "Unable to prepare data!",
  err_data404Grp : "You are not a member of the learning group. Please join first!",
  hapusAccGagal : "Sorry, we are unable to process your request at this time, please try again later",
  err_savingData : "Failed to save data, try again later",

  inf_ujianNull : "There is no data for this exam",
  inf_ujianDone : "You have done this exam",
  inf_emailValid: "Enter a valid email!",
  snk : "Privacy Policy / Terms & Conditions",
  tnc : "I agree to the applicable Terms & Conditions",
  inf_regjudul: "Registration",
  inf_regsukses: "Success, please login",
  inf_sandiPulih :"Password Recovery",
  inf_qlog: "Sign In ? Click here",
  inf_wajib: "Required Information",
  inf_ubhsandi: "Change Password?",
  inf_ubahpsw :"Password changed successfully",
  inf_deskUbhsandi: "Please fill in the information below",
  informasi : "Information",
  profil_update: "Profile Successfully updated",
  foto_profil : "Change Profile Photo",
  txt_loader : "Please wait",
  pahami_quran: "Understand Qur'an",

  inf_endText: "You can improve the Exam Result by repeating it, If you are sure please press OK, your score will be saved.",
  alt_ujianOut: "Are you sure you want to leave the Exam?",
  exit:"Close App?",

  guestAlert:"You are logged in using Guest account, Use a Real Account to access this feature.",
  outError:"An error occurred while logging out, Please try again later",
  nobaner:"No content yet",
  delacctext:"Delete Account?",
  codeWrong:"Code not match, try again...",
  enterCodev : "Please enter the verification code \n we send to your email address. \n \n}",
  notReceivecode: "Don't reveive code?",
  btnVerify : "Verify"
};
