export default {
  lang:'id',
  halo: "Halo",
  gantiBahasa:"Ganti Bahasa",
  pilihBahasa: "Pilih Bahasa",
  pengaturanBahasa:"Pengaturan Bahasa",
  judulApp:"Mari Belajar Al-Quran Dengan BaQi",
  deskBeranda: "Beranda",
  deskProfil: "Profil",
  deskProses: "Kemajuan",
  menuOne : "Memahami Qur'an",
  menuTwo :"Ujian",
  menuTree : "Peringkat",
  menuFour : "Grup",
  deskMenu1: "Memahami Al-Qur'an dengan baik",
  deskMenu2: "Ayo Uji Kemampuanmu",
  deskMenu3: "Lihat Peringkatmu Disini",
  deskMenu4: "Gabung Grup Belajar",
  menuPetro : "Petrofisika & CEOR",
  deskMenuPetro: "Belajar Petrofisika & Chemical EOR",
  judulPetro: "Petrofisika & CEOR",
  menuPetroPetro: "Petrofisika",
  deskMenuPetroPetro: "Belajar Petrofisika",
  menuPetroCEOR: "Chemical EOR",
  deskMenuPetroCEOR: "Belajar Chemical EOR",
  ujianBab: "Ujian Akhir Bab",
  baqi_desk: "Bahasa Qur'an Interaktif",
  fnama : "Nama",
  fnohp : "Nomor Hp (Opsional)",
  femail : "Email",
  infoLogin : "Kamu Masuk Dengan",

  infoLoginform: "Silahkan masuk untuk melanjutkan",
  fpengguna: "Nama Pengguna",
  fsandi: "Kata Sandi",
  lupasandi: "Lupa Kata Sandi?",
  buatakun: "Buat Akun",
  masuk:"Masuk",
  daftar:"Daftar",
  masukdengan: "Masuk Dengan",
  daftardengan: "Daftar Dengan",
  atau: "Atau",
  btnfb : "Masuk dengan Facebook",
  btngoogle : "Masuk dengan Google",
  btnRfb : "Daftar dengan Facebook",
  btnRgoogle : "Daftar dengan Google",
  gueslogin  : "Masuk Sebagai Guest",
  keseluruhan : "Keseluruhan",
  semangat : "Tetap Semangat",
  terimakasih : "Terimakasih",
  st_kerjakan : "Terakhir Dikerjakan",
  st_buatkamu : "Buat Kamu",
  st_notif_prgs : "Belum ada ujian yang dikerjakan",

  skor : "Skor",
  peringkat : "Peringkat",
  totalskor: "Total Skor",

  sandiBaru: "Sandi Baru",
  us_sandi: "Ubah Sandi",
  g_judul : "Daftar Grup",
  g_deskrip : "Grup Tersedia",
  lainnya : "Lainnya",
  gpop_judul : "Kata Sandi Grup",
  gpass_desk : "Masukan password untuk bergabung dengan grup",

  bg_judul : "Bentuk Grup \nKomunitas Belajar",
  bg_fnama: "Nama Grup",
  bg_fdesk: "Deskripsi Grup",
  bg_fpass: "Kata Sandi Grup",
  plc_gnama: "Tulis nama grup anda",
  plc_gdesk: "Tulis deskripsi grup",
  plc_gsandi: "Pastikan bersifat unik",
  plc_popSandi: "Masukan kata sandi dengan benar",
  plc_amnamapg : "Tulis Username",
  plc_nmpengguna : "Tulis nama pengguna",
  plc_sandi: "Tulis kata sandi",
  plc_email: "Tulis alamat email",
  plc_nama: "Nama Lengkap",
  plc_sandiv2: "Pastikan sulit ditebak",
  plc_nmpenggunav2 : "Buat dan jangan mudah ditebak",
  berhasil :"Berhasil",
  g_suksesbuat :"Grup berhasil dibuat...",
  g_mbrkeluar:"Anggota telah dikeluarkan",

  txt_ubh_foto:"Ubah Foto Profil",
  kamera:"Kamera",
  galeri:"Galeri",
  pengaturan: "Pengaturan",
  txt_pengaturan: "Akses ambil foto belum diaktifkan.\nBerikan akses untuk memulai mengambil gambar. Aktifkan akses ambil foto dari Pengaturan.",
  btn_cancel_pgtrn: "Nanti Saja",
  btn_yes_pgtrn: "Aktifkan",

  konfirmasi:"Konfirmasi",
  txt_konfimout:"Apakah anda ingin keluar ?",
  txt_konfimgout: "Apakah anda yakin mengeluarkan anggota ini ?",
  txt_konfimadmout: "Yakin ingin meninggalkan grup? grup akan dihapus",
  txt_btambahkan: "Berhasil ditambahkan",
  txt_konfirmagt : "Tambahkan pengguna ini ke dalam grup?",
  txt_konfirmdelacct : "Yakin ingin menghapus akun anda?, tindakan ini akan menghapus semua data anda secara permanen, tidak bisa dibatalkan!",
  txt_verivNotice : "Jika suatu saat anda ingin kembali menggunakan aplikasi, maka anda harus mendaftar ulang lagi",
  txt_codeResend:"Tidak menerima kode? Kirim ulang",
  hapusAccSukses: "Akun kamu telah kami hapus dari sistem, jika ingin kembali silahkan mendaftar ulang",

  verivicationTitle:"VERIFIKASI",
  lanjut: "Selanjutnya",
  cari : "Cari",
  keluar : "Keluar",
  ubahProfil : "Ubah Profil",
  simpan  : "Simpan",
  batal : "Batal",
  yakin: "Yakin",
  gabung : "Gabung",
  tambah: "Tambah",
  gsaya : "Grup Saya",
  gbuat : "Buat Grup",
  gdetail : "Grup Detail",
  gbergabung: "Grup Bergabung",
  anggota : "Anggota",
  mg_judul : "Menu Grup",
  mg_menusatu : "Tambah Anggota",
  oke:"Oke",
  kembali: "Kembali",
  gcari:"Cari Grup",
  cobalagi : "Coba Lagi",
  selamat: "Selamat",

  ubah: "Ubah",
  verifikasi: "Verifikasi",
  kirim:"Kirim",
  tonton: "Tonton",
  baca : "Baca",
  unduh: "Unduh",
  unduh_sekarang: "Unduh Sekarang",
  ujian: "Ujian",
  pelajaran: "Pelajaran",
  pilih_jenis_ujian:"PILIH JENIS UJIAN",
  txt_pilih_ujian:"Silahkan memilih jenis ujian dan selesaikan dengan baik",
  ujian_akhir :"Ujian Akhir",
  final_test : "TES AKHIR",
  grammar_test : "TES TATA BAHASA",
  tatabahasa: "Tata Bahasa",
  level: "Tingkat",
  pilih_jenis_test : "Pilih Jenis Tes",
  txt_pilih_jenis_test : "Anda harus menyelesaikan semua soal setelah soal muncul",

  err_konek : "Tidak dapat terhubung ke server!",
  err_data: "Gagal menerima data dari server!",
  err_trima: "Tidak dapat menerima data",
  dataNull: "Gagal memuat / Data belum tersedia!",
  err_404: "Tidak ada data ditemukan!",
  err_500: "Terjadi kesalahan pada server!",
  err_500V3: "Terjadi kesalahan pada server, Coba lagi nanti!",
  err_404V2: "Belum ada data ditemukan...",
  err_update: "Gagal Update, coba lagi nanti",
  err_user404:"Pengguna tidak ditemukan!",
  err_404V3 : "Belum ada data untuk halaman ini",
  err_noskor: "Saat ini kamu belum memiliki skor, silahkan mulai ujian untuk mendapatkan skor",
  err_unduh : "Maaf dokumen belum tersedia",
  err_unduhV2: "Maaf, Dokumen yang diminta belum siap",
  err_500V2 : "Terjadi kesalahan teknis!",
  err_404V2Grup : "Password grup salah!",
  err_404V3Grup : "Grup tidak ada!",
  err_403Grup: "Tidak dapat meninggalkan grup. Grup masih memiliki anggota aktif",
  grup_409join: "Kamu telah bergabung digrup ini sebelumnya",
  grup_201join: "Selamat Bergabung, Silahkan cek daftar grup saya",
  err_sandi: "Masukan kata sandi minimal 6 karakter",
  err_grpJudul :"Judul Grup tidak boleh kosong!",
  err_grpDesk :"Deskripsi tidak boleh kosong!",
  err_grpSandi :"Password tidak boleh kosong!",
  err_grpMax: "Grup sudah maksimal batas pembuatan!",
  err_duplikatDesk: "Duplikat Deskripsi, Deskripsi telah digunakan",
  err_batal: "Proses Dibatalkan",
  err_proseson: "Proses sedang dijalankan",
  err_playservice: "Mohon Aktifkan Google Play Service",
  err_prosesoff: "Oops, Ada Kesalahan!",
  err_pu_salah : "Nama Pengguna atau Kata Sandi Salah!",
  err_reg409: "Registrasi Gagal, Nama Pengguna / Email telah digunakan!",
  err_regGagal: "Registrasi Gagal, coba lagi nanti",
  err_namaNull: "Nama tidak boleh kosong!",
  err_hpNull: "Nomor Hp tidak boleh kosong!",
  err_emailNull:"Email tidak boleh kosong!",
  err_emailNsm: "Email yang dimasukan tidak sama!",
  err_unameNull : "Nama Pengguna tidak boleh kosong!",
  err_pswNull   : "Kata Sandi tidak boleh kosong!",
  err_data500Nr : "Tidak dapat menyiapkan data!",
  err_data404Grp : "Kamu tidak terdaftar ke dalam grup belajar. Silahkan bergabung terlebih dahulu!",
  hapusAccGagal : "Maaf, saat ini kami belum dapat memproses permintaan anda, coba lagi nanti",
  err_savingData : "Gagal menyimpan data, coba lagi nanti",

  inf_ujianNull : "Belum ada data untuk ujian ini",
  inf_ujianDone : "Kamu telah mengerjakan ujian ini",
  inf_emailValid: "Masukan email yang valid!",
  snk : "Kebijakan Pribadi / Syarat & Ketentuan",
  tnc : "Saya setuju dengan Syarat & Ketentuan yang berlaku",
  inf_regjudul: "Registrasi",
  inf_regsukses: "Berhasil, silahkan login",
  inf_sandiPulih :"Pemulihan Sandi",
  inf_qlog: "Masuk ? Klik Disini",
  inf_wajib: "Informasi Wajib Disi",
  inf_ubhsandi: "Ubah Kata Sandi?",
  inf_ubahpsw :"Kata Sandi berhasil diubah",
  inf_deskUbhsandi: "Mohon isi informasi dibawah",
  informasi : "Informasi",
  profil_update: "Profil Berhasil di update",
  foto_profil : "Ubah Foto Profil",
  txt_loader : "Tunggu Sebentar",
  pahami_quran: "Memahami Al-Qur'an",

  inf_endText: "Kamu dapat memperbaiki Hasil Ujian dengan mengulanginya, Jika sudah yakin silahkan tekan OKE, Skor kamu akan disimpan.",
  alt_ujianOut: "Yakin ingin meninggalkan Ujian?",
  exit:"Keluar dari Aplikasi?",

  guestAlert:"Kamu masuk menggunakan akun Guest, Gunakan Akun Asli untuk mengakses fitur ini.",
  outError:"Terjadi kesalahan saat Logout, Coba lagi nanti",
  nobaner:"Belum ada konten",
  delacctext:"Hapus Akun?",
  codeWrong:"Code Salah, Coba lagi...",
  enterCodev : "Masukkan kode verifikasi \n yang akan kami kirimkan ke alamat email Anda. \n \n",
  notReceivecode: "Tidak menerima kode?",
  btnVerify : "Verifikasi"
};
